// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/5/2024, 3:36:40 PM
const configMerger = require("/Users/hyegyeonglee/Desktop/dev/portfolio/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/hyegyeonglee/Desktop/dev/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hyegyeonglee/Desktop/dev/portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hyegyeonglee/Desktop/dev/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hyegyeonglee/Desktop/dev/portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hyegyeonglee/Desktop/dev/portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hyegyeonglee/Desktop/dev/portfolio/plugins/**/*.{js,ts,mjs}","/Users/hyegyeonglee/Desktop/dev/portfolio/config/**/*.{js,ts,mjs}","/Users/hyegyeonglee/Desktop/dev/portfolio/composables/**/*.{js,ts,mjs}","/Users/hyegyeonglee/Desktop/dev/portfolio/utils/**/*.{js,ts,mjs}","/Users/hyegyeonglee/Desktop/dev/portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/hyegyeonglee/Desktop/dev/portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/hyegyeonglee/Desktop/dev/portfolio/app.config.{js,ts,mjs}"] }));

module.exports = config
